version: '3.7'

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - "8000:8000"
    command: gunicorn wsgi --worker-class eventlet --bind 0.0.0.0:8000
